DrTests with plugins
juliendelplanque/DrTests pull request #46
Opened 2019-04-25 09:16 UTC by GDayne

2019-04-25 09:22 UTC, juliendelplanque commented on src/BaselineOfDrTests/BaselineOfDrTests.class.st
> +					with: [ spec requires: #('DrTests-TestCoverage') ];
```suggestion
					with: [ spec requires: #('DrTests-TestCoverage' 'DrTests-TestCoverage-MocksForTests') ];
```

2019-04-25 10:09 UTC, juliendelplanque requested changes
Will be ok once the comments integrated.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-CommentsToTests/DTCommentToTest.class.st
>  	cmdConf := DTCommentTestConfiguration
Here, you should not have to instantiate a DTConfiguration, it should be the UI that provide it to you in the first place. I will merge anyway but create an issue for this.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-MocksForTests/MockForCoverage.class.st
> +^ 1 + 1
```suggestion
	^ 1 + 1
```

Formatting.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-MocksForTests/MockForCoverage.class.st
> +^ 1 + anObject
```suggestion
	^ 1 + anObject
```

Formatting.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +	dTconf := DTPluginConfiguration items: {package} packages: {package}.
```suggestion
	"The test classes are in the same package as classes under test."
	dTconf := DTPluginConfiguration items: {package} packages: {package}.
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +	self assert: result percent closeTo: 50
Maybe we should store it as a number between 0 and 1 for the percentage instead of a number between 0 and 100.

A ScaledDecimal or a Fraction object could be used.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +self assert: (result isKindOf: DTTestCoverageResult).
```suggestion
self assert: (result class = DTTestCoverageResult).
```

Check the class is exactly the one expected instead.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +| result|
Format.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +	self assert: (items anyOne name includesSubstring: 'Tests')
Here you should check that the package contains at least one test class instead of checking with the name.

You will also need to modify `#packagesAvailableForAnalysis` implementation.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +				allSatisfy: [ :subResult | subResult isKindOf: DTTreeNode ])
```suggestion
				allSatisfy: [ :subResult | subResult class = DTTreeNode ])
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +				allSatisfy: [ :subResult | subResult isKindOf: DTTreeLeaf ])
```suggestion
				allSatisfy: [ :subResult | subResult class = DTTreeLeaf ])
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +	self deny: (items anyOne name includesSubstring: 'Tests')
Same problem as previously, should check if the package contains TestCase instead.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +	self assert: (items anyOne name includesSubstring: 'Tests')
Same problem as previously, should check if the package contains TestCase instead.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverage.class.st
> +DTTestCoverage >> convertToResultsForDrTests: coverageResult [
I think this should be removed (and in superclasses and classes having DTPlugin as super class as well).

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverage.class.st
> +DTTestCoverage >> itemsToBeAnalysedFor: packagesSelected [
This is to update according to previous comments.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverage.class.st
> +DTTestCoverage >> runCoverage: aDTpluginConfiguration [
Needs some refactoring to:
1. Reduce method size (in LOC) -> split in multiple methods
2. Exclude test methods from Metalinks installation

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverage.class.st
> +	covConf := DTTestCoverageConfiguration
See #48

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverage.class.st
> +DTTestCoverage >> runSuite: aTestSuite withResult: aResult [
See #50

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverage.class.st
> +DTTestCoverage >> runTestSuites: testSuites [
See #50

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverageConfiguration.class.st
> +I am a DTPluginConfiguration.
This line is useless, I would remove it.
We know it inherits from DTPluginConfiguration looking at the class declaration.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverageResult.class.st
> +{ #category : #'as yet unclassified' }
Should be classified.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverageResult.class.st
> +{ #category : #'as yet unclassified' }
Should be classified.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverageResult.class.st
> +{ #category : #'as yet unclassified' }
Should be classified.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverageResult.class.st
> +^methodList
```suggestion
	^methodList
```

Formatting

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestCoverage/DTTestCoverageResult.class.st
> +methodList := aCollectionOfMethods
```suggestion
	methodList := aCollectionOfMethods
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
> +result := plugin runForConfiguration: dTconf .
```suggestion
	result := plugin runForConfiguration: dTconf .
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
> +self assert: (result isKindOf: DTTestsProfilingResult).
```suggestion
	self assert: (result class = DTTestsProfilingResult).
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
> +				allSatisfy: [ :subResult | subResult content duration isKindOf: Duration ])
```suggestion
				allSatisfy: [ :subResult | subResult content duration class = Duration ])
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
> +				allSatisfy: [ :subResult | subResult  isKindOf: DTTreeLeaf  ])
```suggestion
				allSatisfy: [ :subResult | subResult class = DTTreeLeaf  ])
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
> +				allSatisfy: [ :subResult | subResult content isKindOf: DTTestCaseProfilingData  ])
```suggestion
				allSatisfy: [ :subResult | subResult content class = DTTestCaseProfilingData  ])
```

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling-Tests/DTTestProfilingTest.class.st
> +	self assert: (items anyOne name includesSubstring: 'Test')
Same problem as previously, check that it is a test package by looking at test classes inside it.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsProfiling/DTTestsProfiling.class.st
> +	"	self halt."
Can be removed.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests-TestsRunner/DTTestsRunner.class.st
> +	"results subResults
This comment can be removed.

2019-04-25 10:09 UTC, juliendelplanque commented on src/DrTests/DTAbstractTreeNode.class.st
> +I am the abstract superclass for all classes thar are nodes or leafs used to show results.
```suggestion
I am the abstract superclass for all classes that are nodes or leafs used to show results.
```

2019-04-29 09:17 UTC, GDayne commented on src/DrTests-TestCoverage-Tests/DTTestCoverageTest.class.st
> +	self assert: result percent closeTo: 50
implemented as ScaledDecimal

2019-04-29 12:46 UTC, juliendelplanque approved these changes

2019-04-29 12:46 UTC, merged